deploy: framework account website forums blogs exam admin

framework:
	cd dotnetlive.framework && git pull
account:
	cd dotnetlive.account && make deploy
website:
	cd dotnetlive.website && make deploy
forums:
	cd dotnetlive.forums && make deploy
blogs:
	cd dotnetlive.blogs && make deploy
exam:
	cd dotnetlive.exam && make deploy
admin:
	cd dotnetlive.admin && make deploy